# Generated by Django 3.0.6 on 2020-06-29 23:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_cvpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvpost',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cvpost',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
