# Generated by Django 3.0.6 on 2020-07-02 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_cvpostexperience_cvpostskils'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvpostskils',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cvpostskils',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
