# Generated by Django 3.0.6 on 2020-07-08 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200702_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvpostskils',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
